apiVersion: v1
kind: Service
metadata:
  name: catalogo
  labels:
    istio-metrics: 'true'
  namespace: api
spec:
  selector:
    app: catalogo
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      name: http
    - protocol: TCP
      port: 15020
      targetPort: 15020
      name: http-metrics


